### PR TITLE
Fix sort order if data error

### PR DESCRIPTION
**Pull request by mxhash**

### CODE REVIEW

**Review by Al2Klimov — CHANGES_REQUESTED** [review]
I get the point, but I'd add `( )` around `x // y`. Just to be sure that it works and someone who didn't already jump out of the window understands it.

**Review by Al2Klimov — APPROVED** [review]
LGTM

**Comment by Al2Klimov** [comment]
@mxhash Are you sure about the last one?

**Comment by mxhash** [comment]
Not sure but the order is on the same level as '//'. If the logic order is untouched it makes it more readable ;-).

**Pull request merged**
